#Main report value
int16[] Update_date
int16[] recent_indicator
int16[] health_indicator
int16[] life_indicator
int16[] relationship_indicator

#recent result for 1week
int16[] recent_indicator_log

# VISION State Log(ambulation)
int16[] ambulation_log

# VISION State / Log(Face)
int16[] face_recognition_status
int16[] face_recognition_log
  
# Wearable Device State Log
int16[] heartbeat_status
int16[] heartbeat_log
int16[] activity_status
int16[] activity_log

# IoT Manager
int16[] toilet_entree
int16[] action_state
    
# emerg log
int64[] emerg_time_list
int64[] emerg_time_list_duration
